version: "3"
services:
  db:
    image: postgres:11
    container_name: pc_postgres
    ports:
      - 5432:5432
    volumes:
      - ./build/postgres/init:/docker-entrypoint-initdb.d
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    hostname: postgres
    restart: always
    user: root

  web:
    build: ./build/web
    container_name: pc_web
    command: uwsgi --socket :8001 --module mysite.wsgi
    volumes:
      - ./:/code
      - ./static:/static
    expose:
      - "8001"
    depends_on:
      - db
    tty: true

  nginx:
    image: nginx:alpine
    container_name: pc_nginx
    ports:
      - "80:80"
    volumes:
      - ./build/nginx/conf:/etc/nginx/conf.d
      - ./build/nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./static:/static
    depends_on:
      - web

  redis:
    container_name: pc_redis
    image: "redis:alpine"

  celery:
    container_name: pc_celery
    build: ./build/web
    command: celery -A mysite worker -l info
    volumes:
      - ./:/code
    environment:
      - DB_HOST=db
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=password
    depends_on:
      - web
      - db
      - redis

  celery-beat:
    build: ./build/web
    container_name: pc_celery-beat
    command: celery -A mysite beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler --pidfile=
    volumes:
      - ./:/code
    environment:
      - DB_HOST=db
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=password
    depends_on:
      - web
      - db
      - redis
