version: "3"
services:
  db:
    image: postgres:11
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./build/postgres/init:/docker-entrypoint-initdb.d
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    hostname: postgres
    restart: always
    user: root

  app:
    build: ./build/app
    container_name: app
    command: uwsgi --socket :8001 --module mysite.wsgi
    volumes:
      - ./:/app
    expose:
      - "8001"
    depends_on:
      - db
    tty: true

  nginx:
    image: nginx:alpine
    container_name: nginx1
    ports:
      - "80:80"
    volumes:
      - ./build/nginx/conf:/etc/nginx/conf.d
      - ./build/nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./static:/static
    depends_on:
      - app

  redis:
    container_name: redis1
    image: "redis:alpine"

  celery:
    container_name: celery1
    build: ./build/app
    command: celery -A mysite worker -l info
    volumes:
      - ./:/app
    depends_on:
      - app
      - db
      - redis

  celery-beat:
    build: ./build/app
    container_name: celery-beat1
    command: celery -A mysite beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler --pidfile=
    volumes:
      - ./:/app
    depends_on:
      - app
      - db
      - redis
